-- Clean up existing setup
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.families CASCADE;

-- Create Tables
CREATE TABLE public.families (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    invite_code TEXT UNIQUE NOT NULL DEFAULT substring(md5(random()::text) from 1 for 8),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT,
    family_id UUID REFERENCES public.families(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id UUID REFERENCES public.families(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id UUID NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    date DATE NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.families ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their family" ON public.families 
    FOR SELECT USING (id IN (SELECT family_id FROM public.profiles WHERE id = auth.uid()));

CREATE POLICY "Users can view profiles" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update profiles" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert profiles" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Family members view categories" ON public.categories 
    FOR SELECT USING (family_id IN (SELECT family_id FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Family members insert categories" ON public.categories 
    FOR INSERT WITH CHECK (family_id IN (SELECT family_id FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Family members delete categories" ON public.categories 
    FOR DELETE USING (family_id IN (SELECT family_id FROM public.profiles WHERE id = auth.uid()));

CREATE POLICY "Family members view expenses" ON public.expenses 
    FOR SELECT USING (family_id IN (SELECT family_id FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Family members insert expenses" ON public.expenses 
    FOR INSERT WITH CHECK (family_id IN (SELECT family_id FROM public.profiles WHERE id = auth.uid()) AND user_id = auth.uid());
CREATE POLICY "Family members delete expenses" ON public.expenses 
    FOR DELETE USING (family_id IN (SELECT family_id FROM public.profiles WHERE id = auth.uid()));

    -- Drop existing family policies
DROP POLICY IF EXISTS "Users can view their family" ON public.families;
DROP POLICY IF EXISTS "Authenticated users can insert families" ON public.families;
DROP POLICY IF EXISTS "Authenticated users can view families" ON public.families;

-- 1. Allow authenticated users to create a new family
CREATE POLICY "Authenticated users can insert families" 
ON public.families FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- 2. Allow authenticated users to view families (needed for invite code lookup & family details)
CREATE POLICY "Authenticated users can view families" 
ON public.families FOR SELECT 
TO authenticated 
USING (true);


-- Ensure expenses user_id explicitly references public.profiles(id)
ALTER TABLE public.expenses 
DROP CONSTRAINT IF EXISTS expenses_user_id_fkey;

ALTER TABLE public.expenses 
ADD CONSTRAINT expenses_user_id_fkey 
FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;


-- Drop old restrictive profile SELECT policy
DROP POLICY IF EXISTS "Users can view profiles" ON public.profiles;
DROP POLICY IF EXISTS "Users can view their profile" ON public.profiles;
DROP POLICY IF EXISTS "Family members can view each other profiles" ON public.profiles;

-- Create policy allowing users to view profiles of members in the SAME family
CREATE POLICY "Family members can view each other profiles" 
ON public.profiles FOR SELECT 
TO authenticated 
USING (
    -- User can view their own profile
    auth.uid() = id 
    OR 
    -- User can view profiles of members sharing the same family_id
    family_id IN (
        SELECT family_id 
        FROM public.profiles 
        WHERE id = auth.uid()
    )
);


-- ============================================================================
-- 1. CREATE HELPER FUNCTION TO BREAK RECURSION
-- ============================================================================

-- Function to safely fetch current user's family_id without triggering RLS loops
CREATE OR REPLACE FUNCTION public.get_auth_family_id()
RETURNS UUID 
LANGUAGE sql 
SECURITY DEFINER 
STABLE
AS $$
    SELECT family_id FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$;


-- ============================================================================
-- 2. RESET POLICIES ON PROFILES & FAMILIES
-- ============================================================================

-- Drop all existing profile policies
DROP POLICY IF EXISTS "Users can view profiles" ON public.profiles;
DROP POLICY IF EXISTS "Users can view their profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Family members can view each other profiles" ON public.profiles;
DROP POLICY IF EXISTS "Family members can view profiles" ON public.profiles;

-- Create clean Profile Policies (No recursion)
CREATE POLICY "Users can insert their own profile" 
ON public.profiles FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
ON public.profiles FOR UPDATE 
TO authenticated 
USING (auth.uid() = id);

CREATE POLICY "Family members can view profiles" 
ON public.profiles FOR SELECT 
TO authenticated 
USING (
    -- User can view their own profile OR profiles belonging to the same family
    auth.uid() = id 
    OR 
    (family_id IS NOT NULL AND family_id = public.get_auth_family_id())
);


-- Drop all existing family policies
DROP POLICY IF EXISTS "Users can view their family" ON public.families;
DROP POLICY IF EXISTS "Authenticated users can insert families" ON public.families;
DROP POLICY IF EXISTS "Authenticated users can view families" ON public.families;

-- Create clean Family Policies
CREATE POLICY "Authenticated users can insert families" 
ON public.families FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Authenticated users can view families" 
ON public.families FOR SELECT 
TO authenticated 
USING (
    id = public.get_auth_family_id() OR true -- Allows lookup by invite_code during signup
);


-- ============================================================================
-- 3. RESET POLICIES ON CATEGORIES & EXPENSES
-- ============================================================================

-- Categories Policies
DROP POLICY IF EXISTS "Family members view categories" ON public.categories;
DROP POLICY IF EXISTS "Family members insert categories" ON public.categories;
DROP POLICY IF EXISTS "Family members delete categories" ON public.categories;

CREATE POLICY "Family members view categories" ON public.categories 
    FOR SELECT TO authenticated USING (family_id = public.get_auth_family_id());

CREATE POLICY "Family members insert categories" ON public.categories 
    FOR INSERT TO authenticated WITH CHECK (family_id = public.get_auth_family_id());

CREATE POLICY "Family members delete categories" ON public.categories 
    FOR DELETE TO authenticated USING (family_id = public.get_auth_family_id());


-- Expenses Policies
DROP POLICY IF EXISTS "Family members view expenses" ON public.expenses;
DROP POLICY IF EXISTS "Family members insert expenses" ON public.expenses;
DROP POLICY IF EXISTS "Family members delete expenses" ON public.expenses;

CREATE POLICY "Family members view expenses" ON public.expenses 
    FOR SELECT TO authenticated USING (family_id = public.get_auth_family_id());

CREATE POLICY "Family members insert expenses" ON public.expenses 
    FOR INSERT TO authenticated WITH CHECK (family_id = public.get_auth_family_id() AND user_id = auth.uid());

CREATE POLICY "Family members delete expenses" ON public.expenses 
    FOR DELETE TO authenticated USING (family_id = public.get_auth_family_id());


CREATE POLICY "Allow public check for existing emails" 
ON public.profiles FOR SELECT 
TO anon, authenticated 
USING (true);

-- Categories: allow family members to rename categories
DROP POLICY IF EXISTS "Family members update categories" ON public.categories;
CREATE POLICY "Family members update categories" ON public.categories
    FOR UPDATE TO authenticated
    USING (family_id = public.get_auth_family_id())
    WITH CHECK (family_id = public.get_auth_family_id());

-- Expenses: allow family members to edit transactions
DROP POLICY IF EXISTS "Family members update expenses" ON public.expenses;
CREATE POLICY "Family members update expenses" ON public.expenses
    FOR UPDATE TO authenticated
    USING (family_id = public.get_auth_family_id())
    WITH CHECK (family_id = public.get_auth_family_id());


-- Allow family members to update their own family's name
DROP POLICY IF EXISTS "Family members update families" ON public.families;
CREATE POLICY "Family members update families" ON public.families
    FOR UPDATE TO authenticated
    USING (id = public.get_auth_family_id())
    WITH CHECK (id = public.get_auth_family_id());